name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "export const regExp = $(npx browserslist-useragent-regexp --allowHigherVersions);" > supportedBrowsers.js
      - run: echo "export const list = $(npx browserslist --json);" >> supportedBrowsers.js
      - run: cat supportedBrowsers.js
      - name: pull-request
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "My pull request title"
          body: "My pull request body"
          branch: "my-pull-request-base-branch"
          path: "lib/"
          commit-message: "My commit message for uncommitted changes in lib/ folder"
          author: "Nermin <softicnermin@gmail.com>"
          assignees: softicnermin
          update-pull-request-title-and-body: false
      - run: echo "🍏 This job's status is ${{ job.status }}."
