name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "export const regExp = $(npx browserslist-useragent-regexp --allowHigherVersions);" > supportedBrowsers.js
      - run: echo "export const list = $(npx browserslist --json);" >> supportedBrowsers.js
      - run: cat supportedBrowsers.js
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "master"                      # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*

            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "softicnermin"                         # Comma-separated list (no spaces)
          pr_assignee: "softicnermin"                         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_milestone: "Milestone 1"                       # Milestone name
          pr_draft: true                                    # Creates pull request as draft
          pr_allow_empty: true                              # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}      # If blank, default: secrets.GITHUB_TOKEN
      - run: echo "🍏 This job's status is ${{ job.status }}."
